### ISSUE TITLE
Unable to share images direct from the filesystem

### ISSUE THREAD

**Issue by EdGeraghty** [syphon-org/syphon#392]
https://user-images.githubusercontent.com/20861699/139702479-69710aab-f86e-4b02-94d8-8bea3a8b998b.mp4

Trying to upload images direct from the file system gives me a spinning upload ring.

It is, however, possible to share images via the "Gallery".

Logcat below:

```
10-30 10:50:50.014 24009 24034 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/external/images/media' (OS Error: No such file or directory, errno = 2)
10-30 10:50:50.014 24009 24034 E flutter : #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
10-30 10:50:50.014 24009 24034 E flutter : #1      _rootRunUnary (dart:async/zone.dart:1436)
10-30 10:50:50.014 24009 24034 E flutter : <asynchronous suspension>
10-30 10:50:50.014 24009 24034 E flutter :
```

**Comment by notramo** [comment]
It sometimes doesn't even display the spinning loading icon, simply an unresponsive send button.

**Comment by EdGeraghty** [comment]
Fixed at some point in the past!
