### ISSUE TITLE
Windows client cannot use image picker

### ISSUE THREAD

**Issue by EdGeraghty** [syphon-org/syphon#405]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
<asynchronous suspension>
#2      ModalImageOptions.build.<anonymous closure> (package:syphon/views/widgets/modals/modal-image-options.dart:87:43)
<asynchronous suspension>
```

**Comment by EdGeraghty** [comment]
[file_chooser appears to be implemented for Windows](https://github.com/google/flutter-desktop-embedding/pull/651). Am I looking in the wrong place?

**Comment by EdGeraghty** [comment]
Let's keep an eye on https://github.com/flutter/plugins/pull/4863

**Comment by EdGeraghty** [comment]
<img width="114" alt="image" src="https://user-images.githubusercontent.com/20861699/164737532-60b31ad2-d68c-4577-8204-53607cb0c172.png">
