### ISSUE TITLE
Issue selecting and viewing images on Linux

### ISSUE THREAD

**Issue by ereio** [syphon-org/syphon#689]
```
** (syphon:11669): CRITICAL **: 17:16:00.273: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) == 0' failed
flutter: Null check operator used on a null value
flutter: #0      ProfileScreenState.onMounted (package:syphon/views/home/profile/profile-screen.dart:46)
flutter: #1      _StoreStreamListenerState.initState.<anonymous closure> (package:flutter_redux/flutter_redux.dart:475)
flutter: #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
flutter: #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089)
flutter: #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
flutter: #8      _invoke (dart:ui/hooks.dart:151)
flutter: #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
flutter: #10     _drawFrame (dart:ui/hooks.dart:115)
flutter: (elided 3 frames from dart:async)
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by ereio** [comment]
Potentially desktop environment dependent based on the underlying library failure

**Comment by EdGeraghty** [comment]
@ereio the whole widget needs a bit of an overhaul, I was (literally, this morning) doing a bit of an overhaul on `chat-input.dart` but figure we should have a wider conversation about it
