### ISSUE TITLE
Bug related to login on Linux

### ISSUE THREAD

**Issue by mizzunet** [syphon-org/syphon#707]
* clicking on login button does nothing, except the button grey out.
* then reopening syphon take the message screen but wouldn't load/sycn any messages or groups I'm part of.

![image](https://user-images.githubusercontent.com/10193999/177590538-aee7a7fd-fc68-4669-bb81-e448ff056dfa.png)
![image](https://user-images.githubusercontent.com/10193999/177590571-db46ae63-f5f4-42e2-b7b2-0f5cdf3e5e39.png)

Terminal output:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1122)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:628)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:83)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityLinux.checkConnectivity (package:connectivity_plus_linux/src/connectivity.dart:24)
<asynchronous suspension>
#5      ConnectionService.startListener (package:syphon/global/connectivity.dart:22)
<asynchronous suspension>
#6      SyphonState.onStartListeners (package:syphon/views/syphon.dart:136)
<asynchronous suspension>
#7      SyphonState.onInitListeners (package:syphon/views/syphon.dart:105)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SqliteException(1): near "ON": syntax error, SQL logic error or missing database (code 1)
  Causing statement: INSERT INTO auths (id, store) VALUES (?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, store = ?
#0      throwException (package:sqlite3/src/impl/exception.dart:34)
#1      DatabaseImpl._prepareInternal (package:sqlite3/src/impl/database.dart:250)
#2      DatabaseImpl.prepare (package:sqlite3/src/impl/database.dart:152)
#3      _VmDelegate._runWithArgs (package:drift/src/ffi/database.dart:206)
#4      _VmDelegate.runInsert (package:drift/src/ffi/database.dart:219)
#5      _BaseExecutor.runInsert.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:99)
#6      _BaseExecutor._synchronized.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:51)
#7      new Future.sync (dart:async/future.dart:296)
#8      Lock.synchronized.callBlockAndComplete (package:drift/src/utils/synchronized.dart:17)
#9      ServerImplementation._waitForTurn.<anonymous closure> (package:drift/src/remote/server_impl.dart:226)
#10     _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SqliteException(1): near "ON": syntax error, SQL logic error or missing database (code 1)
  Causing statement: INSERT INTO auths (id, store) VALUES (?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, store = ?
#0      throwException (package:sqlite3/src/impl/exception.dart:34)
#1      DatabaseImpl._prepareInternal (package:sqlite3/src/impl/database.dart:250)
#2      DatabaseImpl.prepare (package:sqlite3/src/impl/database.dart:152)
#3      _VmDelegate._runWithArgs (package:drift/src/ffi/database.dart:206)
#4      _VmDelegate.runInsert (package:drift/src/ffi/database.dart:219)
#5      _BaseExecutor.runInsert.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:99)
#6      _BaseExecutor._synchronized.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:51)
#7      new Future.sync (dart:async/future.dart:296)
#8      Lock.synchronized.callBlockAndComplete (package:drift/src/utils/synchronized.dart:17)
#9      ServerImplementation._waitForTurn.<anonymous closure> (package:drift/src/remote/server_impl.dart:226)
#10     _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
```
Info:
OS: Arch Linux
Syphon version: 2.13
Installed by: `yay -S syphon-bin`
WM: river

**Comment by dnisbetjones** [comment]
Tagging @0x1a8510f2 for attention

**Comment by ereio** [comment]
I've fixed this in 0.2.14, we just haven't released it yet. Hoping to get this out soon

**Comment by dnisbetjones** [comment]
Closing with fix imminent

**Comment by ereio** [comment]
very strange, is it the same issue?

The fix was not using the `ON UPDATE` SQL since it's not supported in older versions of sqlite and most linux distros ship with a very old version of it

Is it still showing the error of "near `ON"? There should be a guard clause that runs two separate queries instead of the on update

**Comment by ereio** [comment]
It's to test if you're connected to a network so we don't spam outbound calls to the matrix server and let the user know they're offline.

Mostly useful for mobile when connection can be spotty from wifi or cell, not as much for desktop.

Surprised it's throwing such a large uncaught error. Will add a few fixes to resolve the issue and prevent it from throwing such a large error.

Thanks for finding / bringing up the issue! We appreciate it!
