### ISSUE TITLE
TextSpan error: `Invalid argument(s): string is not well-formed UTF-16`

### ISSUE THREAD

**Issue by EdGeraghty** [syphon-org/syphon#760]
```
======== Exception caught by painting library ======================================================
The following ArgumentError was thrown while building a TextSpan:
Invalid argument(s): string is not well-formed UTF-16

When the exception was thrown, this was the stack: 
#0      ParagraphBuilder.addText (dart:ui/text.dart:3140:7)
#1      TextSpan.build (package:flutter/src/painting/text_span.dart:280:17)
#2      TextPainter._createParagraph (package:flutter/src/painting/text_painter.dart:760:10)
#3      TextPainter.layout (package:flutter/src/painting/text_painter.dart:812:7)
#4      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:645:18)
#5      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:695:5)
#6      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:808:5)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#10     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467:11)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#12     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#13     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:442:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#15     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#18     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#21     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#22     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#23     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
#24     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#30     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#33     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#34     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
#35     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#38     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:240:12)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#41     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#42     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:836:43)
#43     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938:32)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#45     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#46     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:240:12)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#70     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:493:13)
#71     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:241:19)
#72     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:283:12)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#74     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:149:12)
#75     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:386:11)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#77     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:550:13)
#78     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1634:12)
#79     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1541:20)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#81     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#84     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#87     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#90     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#93     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#96     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#99     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#102    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#104    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552:11)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#106    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#109    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#112    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#115    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#116    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#117    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
#118    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#120    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#121    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#122    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
#123    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#125    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#126    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#127    RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:903:45)
#128    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938:32)
#129    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#130    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#131    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:442:14)
#132    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#133    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#134    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#135    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1080:7)
#136    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#137    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#138    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#139    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#140    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#141    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#142    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#144    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467:11)
#145    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#146    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#148    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#149    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#150    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#151    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#152    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#153    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#154    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#155    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#156    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#157    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#158    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#159    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#160    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#161    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#162    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#163    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#164    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#165    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#166    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#167    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#168    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#169    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#170    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#171    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#172    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#173    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#174    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#175    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3815:13)
#176    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#177    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#178    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#179    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#180    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#181    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:856:15)
#182    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#183    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#184    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#185    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#186    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#187    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#188    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#189    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#190    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#191    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#192    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#193    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#194    RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#195    RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#196    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#197    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2027:7)
#198    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1020:18)
#199    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:516:19)
#200    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#201    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#202    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#203    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#204    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#205    _invoke (dart:ui/hooks.dart:145:13)
#206    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#207    _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================
```

No idea where this is coming from, nor how to debug...

**Comment by 0x1a8510f2** [comment]
When does the error/crash happen? Perhaps a decryption error resulting in invalid UTF-16 data?

**Comment by EdGeraghty** [comment]
>Perhaps a decryption error resulting in invalid UTF-16 data?

It's probably exactly that, actually.
